name: three_d_slider
description: "A versatile 3D slider widget for Flutter, perfect for building dynamic, interactive carousels with customizable 3D effects for modern UI designs."
version: 1.0.0
license: MIT

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0